[package]
name = "kgen"
version = "1.0.0"
edition = "2021"
description = "Codegen tool for typescript React projects"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colored = {version = "2.0.0", features = []}